#!/bin/sh

if [ -z "$1" ] ; then
	echo "ERROR: No file search provided"
	exit 1
fi

if [ -z "$2" ] ; then
	echo "ERROR: No output format specified"
	exit 1
fi

if [ -z "$3" ] ; then
	echo "WARNING: No sox options provided"
fi

if [ -z "$4" ] ; then
	echo "WARNING: No name-addendum provided"
fi


echo "" # give me some space

# originally used a FILES variable
# FILES="$(pwd)/$1"
# for f in *$1 #$FILES

COUNT=1; # start a counter
find . -iname "$1" | while read f
do
	echo "File# $COUNT";
	FILENAME=$(basename "$f"); #echo "filename is: $FILENAME";
	BASENAME=${FILENAME%.*}; #echo "basename is: $BASENAME";
	EXT="${FILENAME##*.}"
	CONVERTCODE="sox \"$BASENAME.$EXT\" $3 \"$BASENAME$4.$2\"  -S -V2 $5"
	echo "Convert code:" $CONVERTCODE # just print out the code that will run
	echo "";
	if [ "$5" ] ; then
		echo $CONVERTCODE | /bin/bash # actually run the code if switch is present
	fi
	COUNT=$((COUNT+1)); # increment counter
done
echo ""
if [ -z "$5" ] ; then
	echo "SCRIPT WAS NOT RUN! Add '1' at the end of the command to activate"
fi
echo ""
